version: '3'

services:
  watchtower:
    container_name: watchtower_1
    image: containrrr/watchtower:latest
    hostname: watchdog
    restart: unless-stopped
    environment:
      - WATCHTOWER_CONTAINER_LABEL=all
      - WATCHTOWER_RUN_ONCE=true
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_POLL_INTERVAL=3600
      - WATCHTOWER_INCLUDE_STOPPED=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
